# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - epots

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout Latest Code Version 
      - uses: actions/checkout@v2

      # Install Node 
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      # FIRST: Build Client Side App 
      # Build and Test Node 
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: client 
        
      # Compress Build 
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.2
        with:
          filename: release.zip
          # path: ./build/*
          # directory: client
          path: .
          exclusions: ' *.git* /*node_modules/* .editorconfig /*public/* /*src/*'
      
      # Return Release Artifact 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: epots-app
          path: ./client/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: epots-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'epots'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_05122165818D4CC3B6235E3DDF982495 }}
          package: release.zip

